### ISSUE TITLE
Falsches Image im whomai.yaml

### ISSUE THREAD

**Issue by theRealMightyFly** [ct-Open-Source/k8s-examples#1]
Nach kubectl apply -f whoami.yaml

Events:
  Type     Reason          Age                   From               Message
  ----     ------          ----                  ----               -------
  Normal   Scheduled       5m19s                 default-scheduler  Successfully assigned default/whoami-deployment-7b675b9d69-2mrsk to raspi3
  Normal   Pulling         4m7s (x3 over 5m9s)   kubelet, raspi3    Pulling image "ctmagazin/rpi-whoami"
  Warning  Failed          4m6s (x3 over 4m59s)  kubelet, raspi3    Failed to pull image "ctmagazin/rpi-whoami": rpc error: code = Unknown desc = failed to resolve image "docker.io/ctmagazin/rpi-whoami:latest": no available registry endpoint: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  Warning  Failed          4m6s (x3 over 4m59s)  kubelet, raspi3    Error: ErrImagePull
  Normal   BackOff         4m4s (x6 over 4m45s)  kubelet, raspi3    Back-off pulling image "ctmagazin/rpi-whoami"
  Warning  Failed          4m4s (x6 over 4m45s)  kubelet, raspi3    Error: ImagePullBackOff
  Normal   SandboxChanged  4m3s (x4 over 4m59s)  kubelet, raspi3    Pod sandbox changed, it will be killed and re-created.

=> Problem das in der whoami.yaml ein nicht im docker repo existierendes Image referenziert wird:

IST

 - image: ctmagazin/rpi-whoami 

SOLL

- image: ctmagazin/whoami

https://hub.docker.com/r/ctmagazin/whoami

**Comment by gregorwolf** [comment]
Ist im pull request #2 korrigiert.

**Comment by merlinschumacher** [comment]
Vielen Dank. War noch der falsche Name vom entwickeln drin. Gefixt mit #2
